// <auto-generated />
using System;
using ApiCerveceria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCerveceria.Migrations
{
    [DbContext(typeof(CerveceriaContext))]
    [Migration("20221115235847_Cerveceria")]
    partial class Cerveceria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCerveceria.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            MarcaId = 1,
                            Nombre = "Corona"
                        },
                        new
                        {
                            MarcaId = 2,
                            Nombre = "Pacífico"
                        },
                        new
                        {
                            MarcaId = 3,
                            Nombre = "Cuahutemoc"
                        },
                        new
                        {
                            MarcaId = 4,
                            Nombre = "Psicosis Imperial IPA"
                        },
                        new
                        {
                            MarcaId = 5,
                            Nombre = "Heineken"
                        },
                        new
                        {
                            MarcaId = 6,
                            Nombre = "Sol"
                        },
                        new
                        {
                            MarcaId = 7,
                            Nombre = "Modelo"
                        });
                });

            modelBuilder.Entity("ApiCerveceria.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProvedorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProvedorId");

                    b.HasIndex("TipoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 18,
                            Descripcion = "Desde 1899 y una tradición detrás, Cerveza Sol es la primer cerveza con botella transparente en México.",
                            Imagen = "Sol.jpg",
                            MarcaId = 6,
                            Nombre = "Sol",
                            Precio = 25m,
                            TipoId = 3
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 23,
                            Descripcion = "Nacida para ser leyenda. Tecate cerveza sabe a lo que debe saber una cerveza. Tecate cerveza Ideal para seguir estando juntos aunque sea a la distancia. Tecate Titanium. Tecate Ambar. Tecate Ligth. Tecate Original.",
                            Imagen = "Tecate.jpg",
                            MarcaId = 3,
                            Nombre = "Tecate",
                            Precio = 30m,
                            TipoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 78,
                            Descripcion = "Cerveza Indio es el nombre de una cerveza mexicana de la Cervecería Cuauhtémoc Moctezuma creada en Nuevo León, México en 1893.",
                            Imagen = "Indio.jpg",
                            MarcaId = 3,
                            Nombre = "Indio",
                            Precio = 24m,
                            TipoId = 4
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 12,
                            Descripcion = "Es una cerveza tipo Pilsner de 4.5º de alcohol que actualmente se vende en más de 180 países en los cinco continentes.",
                            Imagen = "Corona.jpg",
                            MarcaId = 1,
                            Nombre = "Corona",
                            Precio = 25m,
                            TipoId = 3
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 88,
                            Descripcion = "Carta Blanca es una cerveza mexicana tipo lager con más de un siglo de tradición cervecera. Con un perfil de sabor equilibrado y refrescante gracias a su proceso de elaboración e ingredientes de primera calidad que la han hecho merecedora de 20 galardones internacionales.",
                            Imagen = "CartaBlanca.jpg",
                            MarcaId = 3,
                            Nombre = "Carta Blanca",
                            Precio = 31m,
                            TipoId = 4
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 90,
                            Descripcion = "Modelo especial, una cerveza pilsner americana, fue la primera cerveza creada y producida por Grupo Modelo en 1925. Relanzada utilizando la misma receta en 2010, Especial tiene un color dorado brillante, y un sabor dulce y bien equilibrado con lúpulos ligeros y un final fresco.",
                            Imagen = "Modelo.jpg",
                            MarcaId = 7,
                            Nombre = "Modelo",
                            Precio = 34m,
                            TipoId = 3
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 54,
                            Descripcion = "Victoria es una deliciosa cerveza tipo Viena que ofrece un sabor único y chingón al estilo mexicano",
                            Imagen = "Victoria.jpg",
                            MarcaId = 7,
                            Nombre = "Victoria",
                            Precio = 25m,
                            TipoId = 4
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 34,
                            Descripcion = "La cerveza Dos Equis lager especial, nació en 1984 de la derivación de la Dos Equis ámbar. Esta marca fue creada en el estado de Veracruz para conmemorar la llegada del siglo veinte. Es una cerveza clara que dejará un toque suave y refrescante en tu paladar",
                            Imagen = "XX.jpg",
                            MarcaId = 5,
                            Nombre = "XX",
                            Precio = 40m,
                            TipoId = 3
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 12,
                            Descripcion = "Bohemia Vienna es una cerveza hecha con maltas caramelo, dulce y chocolate, destacan los aromas ahumados, a nuez y a café. Cerveza con un buen cuerpo, sabores a dulce y granos tostados. Es un estilo de cerveza Vienna – Fue creada en 1841 en Viena, Austria.",
                            Imagen = "Bohemia.jpg",
                            MarcaId = 3,
                            Nombre = "Bohemia",
                            Precio = 25m,
                            TipoId = 4
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 15,
                            Descripcion = "Cerveza Pacífico es la cerveza mexicana tradicional y líder en el noroeste de nuestro país de Grupo Modelo. Creada a principios del siglo XX en la región de Mazatlán, Sinaloa, es de tipo lager y estilo Pilsner, clara, color dorado pálido, muy suave, refrescante y un final muy fresco.",
                            Imagen = "Pacifico.jpg",
                            MarcaId = 2,
                            Nombre = "Pacifico",
                            Precio = 32m,
                            TipoId = 4
                        });
                });

            modelBuilder.Entity("ApiCerveceria.Models.Provedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provedores");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Tipo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoId");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Nombre = "Lager"
                        },
                        new
                        {
                            TipoId = 2,
                            Nombre = "Especial"
                        },
                        new
                        {
                            TipoId = 3,
                            Nombre = "Clara"
                        },
                        new
                        {
                            TipoId = 4,
                            Nombre = "Negras"
                        },
                        new
                        {
                            TipoId = 5,
                            Nombre = "Alemana"
                        });
                });

            modelBuilder.Entity("ApiCerveceria.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Ventas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVenta")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Producto", b =>
                {
                    b.HasOne("ApiCerveceria.Models.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCerveceria.Models.Provedor", null)
                        .WithMany("Productos")
                        .HasForeignKey("ProvedorId");

                    b.HasOne("ApiCerveceria.Models.Tipo", "Tipo")
                        .WithMany("Productos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Ventas", b =>
                {
                    b.HasOne("ApiCerveceria.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCerveceria.Models.Vendedor", "Vendedor")
                        .WithMany("Ventas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Provedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Tipo", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ApiCerveceria.Models.Vendedor", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
